/*++

Copyright (c) 2015  Microsoft Corporation
Copyright (c) 2015  OpenNT Project

Module Name:

    clogerrs.h

Abstract:

    This module defines I/O error log types.

Author:

    Stephanos Io (stephanos) 10-Jun-2015

Revision History:

--*/

#ifndef _CLOGERRS_
#define _CLOGERRS_

#define ERROR_LOG_SECTOR_INVALID            6600
#define ERROR_LOG_SECTOR_PARITY_INVALID     6601
#define ERROR_LOG_SECTOR_REMAPPED           6602
#define ERROR_LOG_BLOCK_INCOMPLETE          6603
#define ERROR_LOG_INVALID_RANGE             6604
#define ERROR_LOG_BLOCKS_EXHAUSTED          6605
#define ERROR_LOG_READ_CONTEXT_INVALID      6606
#define ERROR_LOG_RESTART_INVALID           6607
#define ERROR_LOG_BLOCK_VERSION             6608
#define ERROR_LOG_BLOCK_INVALID             6609
#define ERROR_LOG_READ_MODE_INVALID         6610
#define ERROR_LOG_NO_RESTART                6611
#define ERROR_LOG_METADATA_CORRUPT          6612
#define ERROR_LOG_METADATA_INVALID          6613
#define ERROR_LOG_METADATA_INCONSISTENT     6614
#define ERROR_LOG_RESERVATION_INVALID       6615
#define ERROR_LOG_CANT_DELETE               6616
#define ERROR_LOG_CONTAINER_LIMIT_EXCEEDED  6617
#define ERROR_LOG_START_OF_LOG              6618
#define ERROR_LOG_POLICY_ALREADY_INSTALLED  6619
#define ERROR_LOG_POLICY_NOT_INSTALLED      6620
#define ERROR_LOG_POLICY_INVALID            6621
#define ERROR_LOG_POLICY_CONFLICT           6622
#define ERROR_LOG_PINNED_ARCHIVE_TAIL       6623
#define ERROR_LOG_RECORD_NONEXISTENT        6624
#define ERROR_LOG_RECORDS_RESERVED_INVALID  6625
#define ERROR_LOG_SPACE_RESERVED_INVALID    6626
#define ERROR_LOG_TAIL_INVALID              6627
#define ERROR_LOG_FULL                      6628
#define ERROR_COULD_NOT_RESIZE_LOG          6629
#define ERROR_LOG_MULTIPLEXED               6630
#define ERROR_LOG_DEDICATED                 6631
#define ERROR_LOG_ARCHIVE_NOT_IN_PROGRESS   6632
#define ERROR_LOG_ARCHIVE_IN_PROGRESS       6633
#define ERROR_LOG_EPHEMERAL                 6634
#define ERROR_LOG_NOT_ENOUGH_CONTAINERS     6635
#define ERROR_LOG_CLIENT_ALREADY_REGISTERED 6636
#define ERROR_LOG_CLIENT_NOT_REGISTERED     6636
#define ERROR_LOG_FULL_HANDLER_IN_PROGRESS  6638
#define ERROR_LOG_CONTAINER_READ_FAILED     6639
#define ERROR_LOG_CONTAINER_WRITE_FAILED    6640
#define ERROR_LOG_CONTAINER_OPEN_FAILED     6641
#define ERROR_LOG_CONTAINER_STATE_INVALID   6642
#define ERROR_LOG_STATE_INVALID             6643
#define ERROR_LOG_PINNED                    6644
#define ERROR_LOG_METADATA_FLUSH_FAILED     6645
#define ERROR_LOG_INCONSISTENT_SECURITY     6646
#define ERROR_LOG_APPENDED_FLUSH_FAILED     6647
#define ERROR_LOG_PINNED_RESERVATION        6648

#endif
